#!/bin/bash

# Docker
sudo apt-get install -y \
    apt-transport-https \
    ca-certificates \
    curl \
    gnupg-agent \
    software-properties-common

curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -


# Use the following command to set up the stable repository. 
# To add the nightly or test repository, add the word nightly or test (or both) after the word stable in the commands below. 
# Learn about nightly and test channels.
sudo add-apt-repository \
   "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
   $(lsb_release -cs) \
   stable"

# Docker Engine
sudo apt-get install -y docker-ce docker-ce-cli containerd.io

# test
# sudo docker run hello-world

sudo usermod -aG docker $(whoami)

# systemd
sudo mkdir -p /etc/systemd/system/docker.service.d

dockerconf=/etc/systemd/system/docker.service.d/options.conf
sudo touch $dockerconf
echo "[Service]" | sudo tee -a $dockerconf
echo "ExecStart=" | sudo tee -a $dockerconf
echo "ExecStart=/usr/bin/dockerd -H unix:// -H tcp://0.0.0.0:2375" | sudo tee -a $dockerconf
sudo systemctl daemon-reload
sudo systemctl restart docker

sudo reboot -h now